### ISSUE TITLE
BISQ address verification issue

### ISSUE THREAD

**Issue by feydreva** [madcoin-project/madcoin#2]
hello,

When I enter my MDC address in the Altcoin account of, i get the error Adress validation failed because it does not match the structure of a MDC address :
my address is : mPQVWKBYeaP2An2CRMng1LbAj7kTsH7mNk

http://block.madcoin.life:3001/address/mPQVWKBYeaP2An2CRMng1LbAj7kTsH7mNk

I reported that error on BISQ, but they tell me it s on your side..
https://github.com/bisq-network/exchange/issues/1151

**Comment by madcoin-project** [comment]
bisq still work with the old madcoin chain , they merge our new request and this issue will be fix in next market version release
